### ISSUE TITLE
your xml

### ISSUE THREAD

**Issue by orthagh** [Probesys/glpi-plugins-rgpdtools#1]
I received the submission for the XML : https://raw.githubusercontent.com/Probesys/glpi-plugins-rgpdtools/github/rgpdtools.xml
Please fix the following points before i can validate it:

- the logo should be maybe original and not the same as https://plugins.glpi-project.org/#/plugin/projectbridge
- your versions should be with semantic syntax filtering, ex `~9.5.0` will match all versions of 9.5 (search semver on google for more information)
- please add screenshot(s)

Let me know when it's done

**Comment by felag** [comment]
@orthagh Hello, it has been done.

Thanks and Regards.
