### ISSUE TITLE
Impossible de lancer la commande composer après installation

### ISSUE THREAD

**Issue by felag** [Probesys/glpi-plugins-rgpdtools#3]
Bonjour,

La commande à lancer après installation du plugins, dans le dossier du plugin est la suivante (noter le `.phar`):

`sudo -u www-data ./composer.phar install --no-dev`

Soit il faut changer le message affiché (voir #2) soit il faut renommer le nom de l'exécutable composer (l'utilisation de l'utilisateur www-data n'a pas à être documentée, car elle dépend de l'utilisateur lançant le serveur web).

**Comment by philg38** [comment]
Les chaînes de traduction ont été modifiée dans ce sens et présentent dans la dernière release, je ferme donc le ticket
